version: "1.7"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN
      SUPPORT: $SUPPORT
      OWNER_ID: $OWNER_ID
      SESSION_NAME: $SESSION_NAME
